In [2]:
import torch as t
import torch.nn as nn

In [15]:
class MLPRRegression(nn.Module):
    def __init__(self,input_dim,hidden_dim):
        super().__init__()
        self.layer_1 = nn.Linear(input_dim,hidden_dim,bias = True)
        self.layer_2 = nn.Linear(hidden_dim,1)
        self.sig = nn.Sigmoid()

    def forward(self,x):
        x = self.layer_1(x)
        x = self.sig(x)
        x = self.layer_2(x)
        x = self.sig(x)
        return x

    def show_info(self):
        for name,parameter in self.named_parameters():
            print(name,"\n",parameter)
            print("------------------------------")

In [16]:
a = MLPRRegression(3,4)
b = t.randn(3)

c = a(b)

a.show_info()
print(b)
print(c)

layer_1.weight 
 Parameter containing:
tensor([[-0.1619, -0.2159,  0.3686],
        [-0.1252,  0.2675,  0.4412],
        [ 0.2085, -0.0260,  0.4695],
        [ 0.1912, -0.4532,  0.5234]], requires_grad=True)
------------------------------
layer_1.bias 
 Parameter containing:
tensor([ 0.0812, -0.4685, -0.5238,  0.4578], requires_grad=True)
------------------------------
layer_2.weight 
 Parameter containing:
tensor([[ 0.3363, -0.4650,  0.1796, -0.1539]], requires_grad=True)
------------------------------
layer_2.bias 
 Parameter containing:
tensor([0.3836], requires_grad=True)
------------------------------
tensor([-0.8038, -1.4098,  0.4601])
tensor([0.5960], grad_fn=<SigmoidBackward0>)


In [ ]:
class MLPModel():#这里原来是不用nn.Module的啊，因为前面已经把nn.Module处理过了
    def __init__(self,input_dim,hidden_dim,epoch,learning_rate):
        #初始化参数值
        self.epoches = epoch
        self.lr = learning_rate
        self.model = MLPRRegression(input_dim,hidden_dim)
        self.optimzer = t.optim.SGD(self.model.parameters(),lr = self.lr)
        self.loss_function = t.nn.MSELoss()

    def train(self,x,y):
        losses = []

        for i in range(self.epoches):
            prediction = self.model(x)
            loss = self.loss_function(prediction,y)
        
            self.optimzer.zero_grad()

            loss.backward()

            self.optimizer.step()

            losses.append(loss.item())#把数值从tensor中提取出来（并不是一个数一个数的训的，而是一起训的）

            if i % 500 == 0:
                print("epoch: {}, loss is: {}".format(i,loss.item()))

        return losses
    def test(self,x,y):
        prediction = self.model(x)
        testMSE = self.loss_function(prediction, y)

        return prediction,testMSE