In [21]:
import torch
import torch.nn as nn
import numpy as np
from PIL import Image
from torchvision import transforms
import torch.nn.functional as F

In [26]:
image = Image.open('5.jpg').convert('RGB')
input = transforms.ToTensor()(image).unsqueeze(0)
print(input.shape)
#Conv-1
Conv1 = nn.Conv2d(in_channels=3, out_channels=6, kernel_size=5, stride=1, padding=0)
Nf1 = nn.ReLU()
output1 = Nf1(Conv1(input))
print(output1.shape)

for s,p in Conv1.named_parameters():
    print(s,p.shape)

torch.Size([1, 3, 32, 32])
torch.Size([1, 6, 28, 28])
weight torch.Size([6, 3, 5, 5])
bias torch.Size([6])


In [27]:
#Poo1-1，也相当于一个组件
Pool1 = nn.MaxPool2d((2,2), stride=2, padding=0)
output1 = Pool1(output1)
print(output1.shape)

torch.Size([1, 6, 14, 14])


In [14]:
#pool - test
x = torch.tensor([[3, 3, 2, 1, 0], 
                  [0, 0, 1, 3, 1], 
                  [3, 1, 2, 2, 3], 
                  [2, 0, 0, 2, 2], 
                  [2, 0, 0, 0, 1]], dtype=torch.float64)
x = x.view(1, 5, 5)
print(x.shape)
MP = nn.MaxPool2d(kernel_size= 3, stride=1)
#x = x.unsqueeze(0)
#print(x.shape)
y = MP(x)
print(y.shape)

MP2 = nn.AvgPool2d(kernel_size=3, stride=1)
y = MP2(x)
print(y)

torch.Size([1, 5, 5])
torch.Size([1, 3, 3])
tensor([[[1.6667, 1.6667, 1.6667],
         [1.0000, 1.2222, 1.7778],
         [1.1111, 0.7778, 1.3333]]], dtype=torch.float64)


In [9]:
#pool test2
a = torch.randn(3,5,10)
MP3 = nn.MaxPool2d((5,1))
c = MP3(a)
print(c.shape)

x = torch.rand(1, 3, 7, 7)
MP4 = nn.AvgPool2d(kernel_size=2, stride=2)
print(MP4.forward(x).shape)

torch.Size([3, 1, 10])
torch.Size([1, 3, 3, 3])


In [28]:
#Conv-2
Conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5, stride=1, padding=0)
Nf2 = nn.ReLU()
output2 = Nf2(Conv2(output1))
print(output2.shape)

torch.Size([1, 16, 10, 10])


In [ ]:
#Poo1-2
Pool2 = nn.MaxPool2d((2,2), stride=2, padding=0)#正好会把原来的变成一半
output2 = Pool1(output2)
print(output2.shape)

torch.Size([1, 16, 5, 5])


In [30]:
#Flatten
output3 = output2.view(1, -1)
print(output3.shape)

#FC
FC = nn.Linear(400,10)
output3 = FC(output3)
print("output3 = ", output3)
print(output3.shape)

#SoftMax
output = torch.softmax(output3, dim=1)
print(output)

torch.Size([1, 400])
output3 =  tensor([[-0.0939, -0.0330, -0.0215,  0.0053, -0.0802, -0.0942, -0.0090,  0.0201,
         -0.0088, -0.0705]], grad_fn=<AddmmBackward0>)
torch.Size([1, 10])
tensor([[0.0945, 0.1005, 0.1016, 0.1044, 0.0958, 0.0945, 0.1029, 0.1060, 0.1029,
         0.0968]], grad_fn=<SoftmaxBackward0>)


In [ ]:
# A class implementation
class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels=3,out_channels=6,kernel_size=5,stride=1,padding=0)
        self.pool1 = nn.MaxPool2d((2,2),stride=2,padding=0)
        self.conv2 = nn.Conv2d(in_channels=6,out_channels=16,kernel_size=5,stride=1,padding=0)
        self.pool2 = nn.MaxPool2d((2,2),stride=2,padding=0)
        self.fc = nn.Linear(400,10)
        self.nf = nn.ReLU()

    def forward(self, x): #前向：完成一次从输入端到输出端的流动
        output1 = self.nf(self.conv1(x))
        print(output1.shape)
        output1 = self.pool1(output1)
        print(output1.shape)
        #####end of the first layer
        output2 = self.nf(self.conv2(output1))
        print(output2.shape)
        output2 = self.pool2(output2)
        print(output2.shape)
        #####end of the second layer

        # Flatten
        output3 = output2.view(x.shape[0],-1)#没有直接写1，因为X中可能有很多张图片
        print(output3.shape)
        # FC
        output3 = self.fc(output3)#过一次全连接层
        print(output3.shape)
        # SoftMax
        output = torch.softmax(output3,dim=1)
        return output

image = Image.open('5.jpg').convert('RGB')
input = transforms.ToTensor()(image).unsqueeze(0)
print(input.shape)

model = CNN()
output = model(input)
print(output)

torch.Size([1, 3, 32, 32])
torch.Size([1, 6, 28, 28])
torch.Size([1, 6, 14, 14])
torch.Size([1, 16, 10, 10])
torch.Size([1, 16, 5, 5])
torch.Size([1, 400])
torch.Size([1, 10])
tensor([[0.1001, 0.1055, 0.1310, 0.0797, 0.1164, 0.1158, 0.1083, 0.0993, 0.0757,
         0.0682]], grad_fn=<SoftmaxBackward0>)


In [19]:
image2 = Image.open('3.jpg').convert('RGB')
input2 = transforms.ToTensor()(image2).unsqueeze(0)
print(input2.shape)

new_input = torch.cat([input,input2],0)
print(new_input.shape)

print("--------------------------")
new_output = model(new_input)
print(new_output)
print("--------------------------")


torch.Size([1, 3, 32, 32])
torch.Size([2, 3, 32, 32])
--------------------------
torch.Size([2, 6, 28, 28])
torch.Size([2, 6, 14, 14])
torch.Size([2, 16, 10, 10])
torch.Size([2, 16, 5, 5])
torch.Size([2, 400])
torch.Size([2, 10])
tensor([[0.1001, 0.1055, 0.1310, 0.0797, 0.1164, 0.1158, 0.1083, 0.0993, 0.0757,
         0.0682],
        [0.0954, 0.1061, 0.1219, 0.0850, 0.1264, 0.1231, 0.1063, 0.0963, 0.0737,
         0.0657]], grad_fn=<SoftmaxBackward0>)
--------------------------
